### ISSUE TITLE
Minify directive failed to correctly minify css block

### ISSUE THREAD

**Issue by TooYoungTooSimp** [hacdias/caddy-minify#14]
### 1. What version of Caddy are you using (`caddy -version`)?
caddy 0.10.6

### 2. What are you trying to do?
minify a html file

### 3. What is your entire Caddyfile?
```text
minify
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf Caddyfile

### 5. Please paste any relevant HTTP request(s) here.
curl 127.0.0.1/test.html

### 6. What did you expect to see?
<style>.lr-border{border-left:1px solid rgba(86,61,124,.2);border-right:1px solid rgba(86,61,124,.2)}</style>

### 7. What did you see instead (give full error messages and/or log)?
<style>.lr-border{border-left:1px solid transparent;border-right:1px solid transparent}</style>

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
just write a html file like this
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        .lr-border {
            border-left: 1px solid rgba(86,61,124,.2);
            border-right: 1px solid rgba(86,61,124,.2);
        }
    </style>
</head>
<body>
</body>
</html>
```
and using a Caddyfile with single line: `minify`
then you can reproduce it.

In fact, minify a single css file can produce the same situation.

**Comment by francislavoie** [comment]
So, I actually tried it here: http://go.tacodewolff.nl/minify which is the same backend that this plugin uses, and it seems to work fine there. It might be something already fixed in that lib.

See https://github.com/tdewolff/minify/releases:
>CSS: rgba and hsla now work properly

So I think this plugin just needs to update itself to use the latest from https://github.com/tdewolff/minify 😄 

Edit: Seems it's been reported already that this plugin isn't working, but on the wrong repo: https://github.com/tdewolff/minify/issues/143

**Comment by hacdias** [comment]
I'm gonna check this out

**Comment by hacdias** [comment]
I'm using the latest from version and still get the same output as you...

**Comment by hacdias** [comment]
tdewolff/minify#145

**Comment by hacdias** [comment]
The fix will be available to download in ~15 mins.
